set_property PACKAGE_PIN L16 [get_ports clk_i]
set_property IOSTANDARD LVCMOS33 [get_ports clk_i]

set_property IOSTANDARD LVCMOS33 [get_ports rst_i]
set_property PACKAGE_PIN G15 [get_ports rst_i]
set_property PULLTYPE PULLDOWN [get_ports rst_i]

set_property IOSTANDARD LVCMOS33 [get_ports {gpio_port[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_port[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_port[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_port[0]}]
set_property PACKAGE_PIN M14 [get_ports {gpio_port[0]}]
set_property PACKAGE_PIN M15 [get_ports {gpio_port[1]}]
set_property PACKAGE_PIN G14 [get_ports {gpio_port[2]}]
set_property PACKAGE_PIN D18 [get_ports {gpio_port[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports uart_tx_o]
set_property PACKAGE_PIN V12 [get_ports uart_tx_o]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rx_i]
set_property PACKAGE_PIN W16 [get_ports uart_rx_i]