#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Aug 16 18:07:44 CEST 2026
# SW Build 5076996 on Wed May 22 18:36:09 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_cpu_behav -key {Behavioral:Software:Functional:tb_cpu} -tclbatch tb_cpu.tcl -view /home/daniel/Projects/CPU/integration/TinyMCU.sim/Software/Waveform.wcfg -log simulate.log"
xsim tb_cpu_behav -key {Behavioral:Software:Functional:tb_cpu} -tclbatch tb_cpu.tcl -view /home/daniel/Projects/CPU/integration/TinyMCU.sim/Software/Waveform.wcfg -log simulate.log

